openapi: 3.0.0
components:
  schemas:
    Item:
      allOf:
        - type: object
          properties:
            id:
              type: number
              description: Id of item.
              example: "1"
            title:
              type: string
              description: Title of item.
              example: "Item"
            description:
              type: string
              description: Description of item.
              example: "Description of item"
        - $ref: '#/components/schemas/Item'
    ItemId:
      type: string
      description: Item id
      example: "52"
tags: [
    {
      name: Item,
      description: API for items in the system.
    }
  ]
paths:
  /items:
    get:
      summary: Retrieve a list of Items.
      tags:
        - Item
      description: Retrieve a list of items from API.
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
  /items/{itemId}:
    get:
      summary: Retrieve details of selected Item.
      tags:
        - Item
      description: Retrieve details of selected item from API.
      parameters:
        - name: itemId
          required: true
          in: path
          schema:
            $ref: '#/components/schemas/ItemId'
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/Item'
        